[WARN ] {21/01/2016 15:54:26.569} [localhost-startStop-1] c.m.v.c.m.ActiveManagementCoordinator - A C3P0Registry mbean is already registered. This probably means that an application using c3p0 was undeployed, but not all PooledDataSources were closed prior to undeployment. This may lead to resource leaks over time. Please take care to close all PooledDataSources.
[WARN ] {21/01/2016 15:54:39.646} [localhost-startStop-1] c.m.v.c.m.ActiveManagementCoordinator - A C3P0Registry mbean is already registered. This probably means that an application using c3p0 was undeployed, but not all PooledDataSources were closed prior to undeployment. This may lead to resource leaks over time. Please take care to close all PooledDataSources.
[ERROR] {21/01/2016 23:13:38.153} [http-apr-8080-exec-6] org.dozer.MappingProcessor - Field mapping error -->
  MapId: null
  Type: null
  Source parent class: org.sigmah.server.domain.element.TextAreaElement
  Source field name: length
  Source field type: null
  Source field value: null
  Dest parent class: org.sigmah.shared.dto.element.TextAreaElementDTO
  Dest field name: length
  Dest field type: java.lang.Integer
java.lang.OutOfMemoryError: Java heap space
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_45]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[na:1.8.0_45]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[na:1.8.0_45]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[na:1.8.0_45]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[na:1.8.0_45]
	at java.lang.Class.getMethods(Unknown Source) ~[na:1.8.0_45]
	at java.beans.MethodRef.find(Unknown Source) ~[na:1.8.0_45]
	at java.beans.MethodRef.get(Unknown Source) ~[na:1.8.0_45]
	at java.beans.PropertyDescriptor.getReadMethod(Unknown Source) ~[na:1.8.0_45]
	at org.dozer.propertydescriptor.JavaBeanPropertyDescriptor.getReadMethod(JavaBeanPropertyDescriptor.java:59) ~[dozer-5.5.1.jar:na]
	at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.invokeReadMethod(GetterSetterPropertyDescriptor.java:278) ~[dozer-5.5.1.jar:na]
	at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.getPropertyValue(GetterSetterPropertyDescriptor.java:86) ~[dozer-5.5.1.jar:na]
	at org.dozer.propertydescriptor.GetterSetterPropertyDescriptor.setPropertyValue(GetterSetterPropertyDescriptor.java:105) ~[dozer-5.5.1.jar:na]
	at org.dozer.fieldmap.FieldMap.writeDestValue(FieldMap.java:96) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.writeDestinationValue(MappingProcessor.java:939) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:368) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.map(MappingProcessor.java:267) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:512) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:465) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:307) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.map(MappingProcessor.java:267) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapCustomObject(MappingProcessor.java:512) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:465) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:820) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:894) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapListToList(MappingProcessor.java:730) ~[dozer-5.5.1.jar:na]
[ERROR] {21/01/2016 23:22:29.724} [http-apr-8080-exec-6] o.s.s.handler.CreateEntityHandler - Error while importing file 'a3abec0d-dee0-47de-bbfb-ff95b090640f1453388123975'.
org.dozer.MappingException: java.lang.NoClassDefFoundError: Could not initialize class org.apache.commons.lang3.builder.ToStringBuilder
	at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:82) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:172) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.map(MappingProcessor.java:104) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.map(MappingProcessor.java:99) ~[dozer-5.5.1.jar:na]
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120) ~[dozer-5.5.1.jar:na]
	at org.sigmah.server.mapper.DozerMapper.map(DozerMapper.java:39) ~[DozerMapper.class:na]
	at org.sigmah.server.mapper.DozerMapper.map(DozerMapper.java:129) ~[DozerMapper.class:na]
	at org.sigmah.server.mapper.DozerMapper.mapCollection(DozerMapper.java:60) ~[DozerMapper.class:na]
	at org.sigmah.server.handler.GetProjectsByModelHandler.execute(GetProjectsByModelHandler.java:39) ~[GetProjectsByModelHandler.class:na]
	at org.sigmah.server.handler.GetProjectsByModelHandler.execute(GetProjectsByModelHandler.java:22) ~[GetProjectsByModelHandler.class:na]
	at org.sigmah.server.handler.base.AbstractCommandHandler.execute(AbstractCommandHandler.java:95) [AbstractCommandHandler.class:na]
	at org.sigmah.server.dispatch.impl.UserDispatch.doExecute(UserDispatch.java:301) [UserDispatch.class:na]
	at org.sigmah.server.dispatch.impl.UserDispatch.access$000(UserDispatch.java:34) [UserDispatch.class:na]
	at org.sigmah.server.dispatch.impl.UserDispatch$UserExecutionContext.execute(UserDispatch.java:110) ~[UserDispatch$UserExecutionContext.class:na]
	at org.sigmah.server.dispatch.impl.UserDispatch$UserExecutionContext.execute(UserDispatch.java:100) ~[UserDispatch$UserExecutionContext.class:na]
	at org.sigmah.server.servlet.importer.Importer.getCorrespondancePerSheetOrLine(Importer.java:401) ~[Importer.class:na]
	at org.sigmah.server.servlet.importer.ExcelImporter.getCorrespondances(ExcelImporter.java:62) ~[ExcelImporter.class:na]
	at org.sigmah.server.servlet.importer.ExcelImporter.<init>(ExcelImporter.java:40) ~[ExcelImporter.class:na]
	at org.sigmah.server.handler.GetImportInformationHandler.doImport(GetImportInformationHandler.java:89) [GetImportInformationHandler.class:na]
	at org.sigmah.server.handler.GetImportInformationHandler.execute(GetImportInformationHandler.java:55) [GetImportInformationHandler.class:na]
	at org.sigmah.server.handler.GetImportInformationHandler.execute(GetImportInformationHandler.java:40) [GetImportInformationHandler.class:na]
	at org.sigmah.server.handler.base.AbstractCommandHandler.execute(AbstractCommandHandler.java:95) [AbstractCommandHandler.class:na]
	at org.sigmah.server.dispatch.impl.UserDispatch.doExecute(UserDispatch.java:301) [UserDispatch.class:na]
	at org.sigmah.server.dispatch.impl.UserDispatch.execute(UserDispatch.java:228) [UserDispatch.class:na]
	at org.sigmah.server.dispatch.SecureDispatchServlet.execute(SecureDispatchServlet.java:148) [SecureDispatchServlet.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569) [gwt-servlet-2.4.0.jar:na]
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208) [gwt-servlet-2.4.0.jar:na]
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248) [gwt-servlet-2.4.0.jar:na]
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62) [gwt-servlet-2.4.0.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [servlet-api.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [guice-servlet-3.0.jar:na]
	at org.sigmah.server.servlet.filter.CacheFilter.doFilter(CacheFilter.java:120) [CacheFilter.class:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89) [guice-persist-3.0.jar:na]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.22]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.22]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.22]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.22]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.22]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.22]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617) [catalina.jar:8.0.22]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.22]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.22]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-coyote.jar:8.0.22]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-coyote.jar:8.0.22]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2463) [tomcat-coyote.jar:8.0.22]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2452) [tomcat-coyote.jar:8.0.22]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_45]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.22]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_45]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.commons.lang3.builder.ToStringBuilder
	at org.sigmah.server.domain.base.AbstractEntity.toString(AbstractEntity.java:32) ~[AbstractEntity.class:na]
	at org.dozer.util.LogMsgFactory.createFieldMappingErrorMsg(LogMsgFactory.java:48) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:314) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.map(MappingProcessor.java:267) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196) ~[dozer-5.5.1.jar:na]
	at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170) ~[dozer-5.5.1.jar:na]
	... 63 common frames omitted
